algoan/rest-nodejs

- src/core/BanksUser.ts
- src/lib/Algoan.dto.ts
- test/bank-user.test.ts
Adds an update method to the banks user class
Resolves #2
> feat(algoan): add update method to banks user class

- src/core/BanksUser.ts
- src/lib/Algoan.dto.ts
- src/lib/Algoan.interface.ts
- test/bank-user.test.ts
- test/samples/banks-users.ts
Adds the createTransaction and createAccounts methods to the BanksUser class
Resolves #4
> Add createTransaction and createAccount to BanksUser

- src/core/index.ts
> fix: export banksUser interface

- src/lib/Algoan.dto.ts
- src/lib/Algoan.enum.ts
- src/lib/Algoan.interface.ts
- test/bank-user.test.ts
- test/samples/banks-users.ts
> Export banks user status as enum

- src/lib/Algoan.interface.ts
> fix: banksUserAccountWithTransactions extends correct interface

- src/core/BanksUser.ts
- src/lib/Algoan.interface.ts
> Fix: change debited account id to non-required

- src/core/BanksUser.ts
- test/bank-user.test.ts
Added BanksUser API functions calls
Two new functions are added in BanksUser.ts:
- `getAccountsByID` corresponding to: https://developers.algoan.com/api/#operation/getbankAccounts
- `getTransactionsByIds` corresponding to: https://developers.algoan.com/api/#operation/getTransactions
Not all functions related to the aggregation manager API are present. They should be added. In addition, they have become essential for us.
- [x ] New feature (non-breaking change which adds functionality)
> feat(banks-users): added API functions for GET Accs and GET Trans

- src/core/BanksUser.ts
- src/lib/Algoan.enum.ts
- src/lib/Algoan.interface.ts
Rectified the BanksUser model
Rectified the BanksUser model
New type `RegularCashFlowOperation` for better structure
Removed the mandatory nature of `alerts` in BanksUser/Analysis
Better API conformity
> feat(lib): added GET DTO + rectified Interfaces

- src/RequestBuilder.ts
Fixes a bug where the `refresh_token` grant type could not be called
> fix(request-builder): add a missing property

- src/core/ServiceAccount.ts
Add the property `config` to the  `serviceAccount` interface. This object aims to hold some information for the `serviceAccount`'s configuration
> feat(serviceaccount): add the property config to the serviceAccount

- src/core/Application.ts
- src/core/ServiceAccount.ts
- src/lib/Algoan.dto.ts
- src/lib/Application.interface.ts
- src/lib/index.ts
- test/application.test.ts
- test/samples/application.ts
- test/service-account.test.ts
Add the [application](https://developers.algoan.com/api/#tag/Application) class
- Add two APIs related to the application
- [`GET /applications/:id`](https://developers.algoan.com/api/#operation/getApplicationProgress)
- [`PATCH /applications/:id`](https://developers.algoan.com/api/#operation/updateApplicationValidation)
> [FEAT] Application API

- src/core/ServiceAccount.ts
- src/core/Signature.ts
- test/service-account.test.ts
- test/signature.test.ts
The previous implementation takes a single signature but Algoan API [requires an array of signatures](https://stg-docs.int.algoan.net/api/#operation/createSignatureDocument).
> fix: fix create signatures API

- src/core/ServiceAccount.ts
- src/lib/Algoan.interface.ts
- test/samples/service-accounts.ts
- test/service-account.test.ts
Fix a bug on the ServiceAccount class
Impossible to retrieve a service account config, because it was not initiated in the class constructor.
> fix(service-account): add config into the class property

- src/lib/Application.interface.ts
Add the bic to the application's interface
> [FIX]: Update the application's interface

- src/core/BanksUser.ts
- src/lib/BanksUser.interface.ts
Update the `callbackUrl` from the Banks User model as optional
> fix(banks-user): callbackUrl is an optional parameter

- src/lib/Algoan.dto.ts
Add new property in the account model `owner.name` to add user personal information.
> feat(accounts): add owner name of account

- src/lib/Algoan.dto.ts
App the applicationId in the PostBanksUserDTO
> [FEAT] Update the PostBanksUserDTO

- src/lib/BanksUser.interface.ts
- test/samples/banks-users.ts
Add the clientId linked with the token to authenticate on budget-insight
BREAKING CHANGE: clientId is new and mandatory
> feat(banks-user): add clientId to budget-insight plugIn

- src/core/BanksUser.ts
- src/lib/Algoan.dto.ts
- src/lib/BanksUser.interface.ts
Add the trigger `adenTriggers.bankreaderConfigurationRequired`  in:
- The `BanksUser` class
- The `PostBanksUserDTO`
- The `IBanksUser` interface
> [FEAT]: Update the BanksUser 

- src/Algoan.ts
I forgot to include the API version into the RequestBuilder class of Algoan...
> fix(algoan): add version to the RequestBuilder instance of Algoan class

- src/core/ServiceAccount.ts
In order to use the `initRestHooks` with another API version, adjust the `ServiceAccount` class to allow version
> fix(service-account): fetch and inject api version

- src/core/index.ts
Add missing export in order to use the Application
In order for a connector to use this _NodeJS Algoan API SDK_., we need to be able to import the Application. Therefore the missing export has been added in the`src/core/index.ts`
> fix(application): add missing export

- src/core/ServiceAccount.ts
- src/lib/Algoan.enum.ts
Add the new V2 events :
- aggregator_link_required
- bank_details_required
This change is required to use the V2 in the connectors
> [FEAT] Update the EventName enum

- src/RequestBuilder.ts
- test/request-builder.test.ts
- test/utils/fake-server.utils.ts
Regenarate access token if the refresh fails.
This fix aims to add a fallback in case the refresh is throwing an error, if the keycloak instance is not able to refresh because of invalid session for example.
> [FIX] regenerate access token

- src/lib/Algoan.dto.ts
- src/lib/BanksUser.interface.ts
Update banks user account dto/interface
- add field `number` to banks user account dto/interface 
Being able to retrieve account number during aggregation.
Those dto/interface are used in `nestjs-budget-insight-connector`, it's why I need to update it.
> [FEAT] update banks user account dto/interface

- package-lock.json
- package.json
- src/RequestBuilder.ts
- Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) via the trim function.
- Affected versions of this package are vulnerable to Server-Side Request Forgery (SSRF). An attacker is able to bypass a proxy by providing a URL that responds with a redirect to a restricted host or IP address.
> Upgrade axios version

- src/lib/Algoan.interface.ts
We added in this PR the IWidgetConfig interface to the IServiceAccount interfacE.
> [TP-11345] Add the widget interface
